### ISSUE TITLE
all-the-icons

### ISSUE THREAD

**Issue by ksexton** [daviwil/runemacs#1]
Might want to install all-the-icons package.  Think you have the fonts available from your main installation but they might not be installed one new users machines.

Something like this should work:

```
(use-package all-the-icons
  :if (display-graphic-p)
  :commands all-the-icons-install-fonts
  :init
  (unless (find-font (font-spec :name "all-the-icons"))
    (all-the-icons-install-fonts t)))

(use-package all-the-icons-dired
  :if (display-graphic-p)
  :hook (dired-mode . all-the-icons-dired-mode))
```

**Comment by daviwil** [comment]
Thanks @ksexton!  You're right, I think the font is being picked up automatically from my distro.  I'll mention this in the next stream and give credit to you!

**Comment by daviwil** [comment]
Thanks again for the help!  I've [added `all-the-icons`](https://github.com/daviwil/runemacs/blob/3eae98aa93db6d24f02b7973d9d10ca667353830/init.el#L69-L75) to the config in this repo and I'll mention it on [today's stream](https://youtu.be/xaZMwNELaJY).

**Comment by sid-agrawal** [comment]
For windows:
1. Download the font to a dir of your choise.
2. Follow instructions here to help windows find it: https://www.digitaltrends.com/computing/how-to-install-fonts-in-windows-10/

**Comment by Skyy93** [comment]
The all-the-icons package doesnt work very well with WSL. After some research in different github issues I think this is due to the terminal behaviour of WSL.
