### ISSUE TITLE
Keyboard wrong language

### ISSUE THREAD

**Issue by ghost** [daviwil/runemacs#77]
I am being stumped by an issue that I feel should have an easy solution.

My PC runs Arch and Gnome and everything is fine with this. Have only been using Emacs for a few days and following your excellent videos I decided to to try EXWM and have that running great on a dual monitor setup.

The problem is that every time I log into EXWM my keyboard is being changed to a US layout instead of UK and I cannot find what is causing it or how to stop it. Have gone through all the configs and tried an ,xinitrc but nothing works. Logging back into Gnome and everything is fine again.

I cannot find any way of stopping this from happening and would appreciate any suggestions.

Thanks :-)

**Comment by glencjones** [comment]
create a file .Xkbmap  [ hidden file . ] in your root directory.
content of file needs to be just "gb".

search X, X11,X.org configuration for more help as X is what's underpinning this.

Hope that helps.

**Comment by ghost** [comment]
So easy when you know how lol.

You sir, are a diamond. Thank you
