### ISSUE TITLE
Broken link for the notes of Hey  "Emacs, Don’t Move My Windows!"

### ISSUE THREAD

**Issue by aweinstein** [daviwil/runemacs#78]
The notes corresponding to the Emacs Tips video 8 "Hey Emacs, Don't Move My Windows!" points to a non-existent file. It points to:

 https://github.com/daviwil/emacs-from-scratch/blob/f4918aadf6970b098999d28bdbc212942aa62b80/show-notes/Emacs-Tips-DisplayBuffer-01.org

I think it should point to:

https://github.com/daviwil/emacs-from-scratch/blob/f4918aadf6970b098999d28bdbc212942aa62b80/show-notes/Emacs-Tips-DisplayBuffer-1.org

(There is an additional zero in the wrong file name.)

**Comment by aweinstein** [comment]
It seems that for some reason I was looking into an old version. The current version is OK.

**Comment by daviwil** [comment]
Great, thanks for letting me know!
